### ISSUE TITLE
chibios error on setup on OSX

### ISSUE THREAD

**Issue by davidbuzz** [Zubax/px4esc#34]
I needed to run "git submodule update --init --recursive" twice bcause I got this first time: 

Submodule 'chibios' (https://github.com/Zubax/ChibiOS) registered for path 'chibios'
Cloning into 'chibios'...
fatal: unable to access 'https://github.com/Zubax/ChibiOS/': Server aborted the SSL handshake
fatal: clone of 'https://github.com/Zubax/ChibiOS' into submodule path 'chibios' failed
Failed to recurse into submodule path 'firmware/zubax_chibios'

not sure if it's just me, but thought I'd report it anyway.

**Comment by pavel-kirienko** [comment]
Nah, it's just your Internet connection had a transient failure.
