### ISSUE TITLE
where to get corrrect arm-non-eabi-gcc version ( 5.4 ) from..? 

### ISSUE THREAD

**Issue by davidbuzz** [Zubax/px4esc#35]
readme doesn't provide any hints on where to get the specific version of gcc from. eventually I found it here for OSX/homebrew, but don't know if this is the preferred method: 
https://github.com/osx-cross/homebrew-arm

**Comment by pavel-kirienko** [comment]
Here: https://launchpad.net/gcc-arm-embedded. You need version 5.3 or later. I'll update README in a sec
