### ISSUE TITLE
./zubax_chibios/tools/blackmagic_flash.sh  does not work under OSX

### ISSUE THREAD

**Issue by davidbuzz** [Zubax/px4esc#37]
readlink command does not have a -f parameter in osx; 
the path to the blackmagic is not in /dev/serial/etc    it/s just /dev/cu.usbmodemE2C5AXX1  or similar ; 
their is a reportedly incorrect use of redirection on the > $tmpfile <<EOF line

( I'm making a python variant of that script now ) .

**Comment by pavel-kirienko** [comment]
https://github.com/Zubax/zubax_chibios/pull/2
https://github.com/Zubax/zubax_chibios/pull/3

**Comment by davidbuzz** [comment]
pleas re-open issue, it's still busted: 
```./zubax_chibios/tools/blackmagic_flash.sh 
Using port: /dev/cu.usbmodemDDDFC2D1
ls: ../../build/*.elf: No such file or directory
   text	   data	    bss	    dec	    hex	filename
 246676	  12246	  82924	 341846	  53756	build/compound.elf
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
./zubax_chibios/tools/blackmagic_flash.sh: line 35: $tmpfile: ambiguous redirect
arm-none-eabi-gdb: option `-x' requires an argument
Use `arm-none-eabi-gdb --help' for a complete list of options.

**Comment by davidbuzz** [comment]
this issue is fixed in https://github.com/Zubax/zubax_chibios/commit/758f0110cf854aec0467c5f7b438f6e92b4e10b8   closing.
